[tool.ruff]
# 目标Python版本
target-version = "py310"
# 缩进宽度为 2 个空格
indent-width = 2
# 每行长度为 150 个字符
line-length = 150

[tool.ruff.format]
# 缩进风格为空格
indent-style = "space"
# 引号风格为双引号
quote-style = "double"